export function MapListingRow(row: any) {
  return {
    listingId: row.listing_id,
    listingTitle: row.listing_title,
    visits: row.visits,
    isFeatured: row.is_featured,
    effectiveDiscount: row.effective_discount,
    primaryImage: row.primary_image,
    status: row.status,
    activationDate: row.activation_date,
    archivedOn: row.archived_on,
    isDeleted: row.is_deleted,
    listedQty: row.listed_qty,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    effectivePrice: row.effective_price,
    conditionName: row.condition_name,
    rating: row.rating,
    totalReviews: row.total_reviews,
    totalRatings: row.total_ratings,
    location: {
      address: row.address,
      locationNick: row.location_nick,
      latitude: row.latitude,
      longitude: row.longitude,
      city: {
        cityId: row.city_id,
        cityName: row.city_name,
        isActiveForDelivery: row.is_active_for_delivery,
      },
    },
    shop: {
      shopId: row.shop_id,
      shopName: row.shop_name,
      logoPath: row.logo_path,
      username: row.username,
      onTrial: row.on_trial,
      onPayment: row.on_payment,
    },
    category: row.category_id,
    categoryName: row.category_name,
    color: row.color_id,
    colorName: row.color_name,
  };
}
