export const COLUMNS_FOR_WISHLIST = {
  listing: {
    listingId: true,
    listingTitle: true,
    isFeatured: true,
    effectiveDiscount: true,
    listingPrice: {
      onlinePrice: true,
      discountValue: true,
      discountUnit: true,
    },
    rating: true,
    totalReviews: true,
    totalRatings: true,
    effectivePrice: true,
    status: true,
    primaryImage: true,
    activationDate: true,
    listedQty: true,
    item: { itemId: true, quantity: true },
    conditionId: true,
    conditionName: true,
    url: true,
    location: {
      city: {
        cityId: true,
        cityName: true,
      },
    },
  },
};
export const COLUMNS_FOR_RESERVATIONS = {
  listing: {
    listingId: true,
    isFeatured: true,
    effectiveDiscount: true,
    listingPrice: {
      onlinePrice: true,
      discountValue: true,
      discountUnit: true,
    },
    listedQty: true,
    listingTitle: true,
    effectivePrice: true,
    rating: true,
    totalReviews: true,
    totalRatings: true,
    item: { itemId: true, quantity: true },
    status: true,
    primaryImage: true,
    activationDate: true,
    location: {
      city: {
        cityId: true,
        cityName: true,
      },
    },
    category: true,
    categoryName: true,
    color: true,
    colorName: true,
    url: true,
  },
};
export const COLUMNS_FOR_PDP = {
  listingId: true,
  listingTitle: true,
  url: true,
  visits: true,
  isFeatured: true,
  effectiveDiscount: true,
  listingPrice: {
    listing: true,
    onlinePrice: true,
    discountValue: true,
    discountUnit: true,
  },
  primaryImage: true,
  status: true,
  activationDate: true,
  archivedOn: true,
  isDeleted: true,
  listedQty: true,
  createdAt: true,
  updatedAt: true,
  effectivePrice: true,
  conditionName: true,
  listingText: {
    listing: true,
    notes: true,
    description: true,
  },
  listingMetadata: {
    listing: true,
    metaKey: true,
    metaValue: true,
  },
  rating: true,
  totalReviews: true,
  totalRatings: true,
  item: { itemId: true, quantity: true },
  images: {
    images_id: true,
    img0: true,
    img1: true,
    img2: true,
    img3: true,
    img4: true,
    img5: true,
    img6: true,
    img7: true,
    img8: true,
    img9: true,
    isImageUploaded: true,
  },
  location: {
    address: true,
    locationNick: true,
    latitude: true,
    longitude: true,
    city: {
      cityId: true,
      cityName: true,
    },
  },
  shop: {
    shopId: true,
    shopName: true,
    logoPath: true,
    username: true,
    onTrial: true,
    onPayment: true,
    shopOption: {
      id: true,
      isD4uEnabled: true,
      isD4uModuleIncluded: true,
    },
  },
  category: true,
  categoryName: true,
  color: true,
  colorName: true,
  devicePorts: {
    portName: true,
  },
};

export const CATEGORY_SPEC_FIELDS = {
  Mobile: {
    isPtaApproved: true,
    listing: true,
    model: true,
    brand: true,
    screenSize: true,
    processor: true,
    refreshRate: true,
    resolution: true,
    isTouchScreen: true,
    cameraType: true,
    fingerprint: true,
    speaker: true,
    batteryType: true,
    batteryCapacity: true,
    screenType: true,
    cameraSpecs: true,
    screenProtection: true,
    simType: true,
    bodyType: true,
    isESim: true,
    networkBand: true,
    ramCapacity: true,
    primaryStorageCapacity: true,
  },
  Tablet: {
    isPtaApproved: true,
    model: true,
    brand: true,
    listing: true,
    screenSize: true,
    processor: true,
    refreshRate: true,
    resolution: true,
    isTouchScreen: true,
    cameraType: true,
    fingerprint: true,
    speaker: true,
    batteryType: true,
    batteryCapacity: true,
    screenType: true,
    cameraSpecs: true,
    screenProtection: true,
    simType: true,
    bodyType: true,
    isESim: true,
    networkBand: true,
  },
  Laptop: {
    listing: true,
    batteryCapacity: true,
    batteryType: true,
    bodyType: true,
    brand: true,
    cameraSpecs: true,
    fingerprint: true,
    generation: true,
    graphicsCardMemory: true,
    graphicsCardName: true,
    graphicsCardType: true,
    isBacklitKeyboard: true,
    isESim: false,
    isSmartTv: false,
    isTouchScreen: true,
    isWebcam: true,
    keyboard: true,
    laptopType: true,
    model: true,
    operatingSystem: true,
    primaryStorageCapacity: true,
    primaryStorageType: true,
    processor: true,
    ramCapacity: true,
    ramType: true,
    refreshRate: true,
    resolution: true,
    screenProtection: true,
    screenSize: true,
    screenType: true,
    secondaryStorageCapacity: true,
    secondaryStorageType: true,
    simType: false,
    speaker: true,
    tvMonitorType: false,
  },
  Desktop: {
    listing: true,
    brand: true,
    desktopType: true,
    generation: true,
    graphicsCard: true,
    graphicsCardMemory: true,
    graphicsCardName: true,
    graphicsCardType: true,
    isTouchScreen: true,
    keyboard: true,
    model: true,
    processor: true,
    primaryStorageCapacity: true,
    primaryStorageType: true,
    ramCapacity: true,
    ramType: true,
    resolution: true,
    secondaryStorageCapacity: true,
    secondaryStorageType: true,
    screenSize: true,
    screenType: true,
    speaker: true,
  },
  'TV / Moniter': {
    listing: true,
    model: true,
    brand: true,
    screenSize: true,
    speaker: true,
    refreshRate: true,
    resolution: true,
    screenType: true,
    displayType: true,
    isSmartTv: true,
    isTvCertified: true,
    isWebcam: true,
    tvMonitorType: true,
    operatingSystem: true,
  },
  Accessories: {
    listing: true,
    accessoryType: true,
    brand: true,
    model: true,
  },
};

export const LISTINGS_COLUMNS = {
  listingId: true,
  listingTitle: true,
  visits: true,
  isFeatured: true,
  effectiveDiscount: true,
  primaryImage: true,
  status: true,
  url: true,
  activationDate: true,
  archivedOn: true,
  isDeleted: true,
  listedQty: true,
  createdAt: true,
  updatedAt: true,
  effectivePrice: true,
  listingPrice: {
    onlinePrice: true,
  },
  item: { itemId: true },
  conditionName: true,
  rating: true,
  totalReviews: true,
  totalRatings: true,
  location: {
    address: true,
    locationNick: true,
    latitude: true,
    longitude: true,
    city: {
      cityId: true,
      cityName: true,
    },
  },
  shop: {
    shopId: true,
    shopName: true,
    logoPath: true,
    username: true,
    onTrial: true,
    onPayment: true,
    shopOption: {
      id: true,
      isD4uEnabled: true,
      isD4uModuleIncluded: true,
    },
  },
  category: true,
  categoryName: true,
  color: true,
  colorName: true,
};

export const RELATED_LISTINGS_COLUMNS = {
  listingId: true,
  listingTitle: true,
  url: true,
  visits: true,
  isFeatured: true,
  effectiveDiscount: true,
  primaryImage: true,
  status: true,
  activationDate: true,
  archivedOn: true,
  isDeleted: true,
  listedQty: true,
  createdAt: true,
  updatedAt: true,
  effectivePrice: true,
  listingPrice: {
    onlinePrice: true,
  },
  item: { itemId: true },
  conditionName: true,
  rating: true,
  totalReviews: true,
  totalRatings: true,
  category: true,
  categoryName: true,
  color: true,
  colorName: true,
  listingSpecification: {
    brand: true,
    model: true,
    accessoryType: true,
  },
  location: {
    address: true,
    locationNick: true,
    latitude: true,
    longitude: true,
    city: {
      cityId: true,
      cityName: true,
    },
  },
  shop: {
    shopId: true,
    shopName: true,
    logoPath: true,
    username: true,
    onTrial: true,
    onPayment: true,
    shopOption: {
      id: true,
      isD4uEnabled: true,
      isD4uModuleIncluded: true,
    },
  },
};

export const PDP_LISTING_COLUMNS = {
  ...COLUMNS_FOR_PDP,
  isPtaApproved: true,
  listing: true,
  model: true,
  brand: true,
  screenSize: true,
  processor: true,
  refreshRate: true,
  resolution: true,
  isTouchScreen: true,
  cameraType: true,
  fingerprint: true,
  speaker: true,
  batteryType: true,
  batteryCapacity: true,
  screenType: true,
  cameraSpecs: true,
  screenProtection: true,
  simType: true,
  bodyType: true,
  isESim: true,
  networkBand: true,
  ramCapacity: true,
  primaryStorageCapacity: true,
  generation: true,
  graphicsCardMemory: true,
  graphicsCardName: true,
  graphicsCardType: true,
  isBacklitKeyboard: true,
  isSmartTv: false,
  isWebcam: true,
  keyboard: true,
  laptopType: true,
  operatingSystem: true,
  primaryStorageType: true,
  ramType: true,
  secondaryStorageCapacity: true,
  secondaryStorageType: true,
  tvMonitorType: false,
  desktopType: true,
  graphicsCard: true,
  displayType: true,
  isTvCertified: true,
  accessoryType: true,
};

export const FEATURED_LISTINGS_COLUMNS = {
  id: true,
  featuredSince: true,
  allowedDuration: true,
  createdAt: true,
  updatedAt: true,
  isDeleted: true,
  listing: {
    listingId: true,
    listingTitle: true,
    url: true,
    isFeatured: true,
    effectiveDiscount: true,
    effectivePrice: true,
    listingPrice: {
      onlinePrice: true,
    },
    rating: true,
    totalReviews: true,
    totalRatings: true,
    status: true,
    primaryImage: true,
    activationDate: true,
    listedQty: true,
    item: { itemId: true, quantity: true, isDeleted: true },
    conditionId: true,
    conditionName: true,
    category: true,
    categoryName: true,
    color: true,
    colorName: true,
    shop: {
      shopId: true,
      shopName: true,
      logoPath: true,
      username: true,
      onTrial: true,
      onPayment: true,
      shopOption: {
        id: true,
        isD4uEnabled: true,
        isD4uModuleIncluded: true,
      },
    },
    location: {
      address: true,
      locationNick: true,
      latitude: true,
      longitude: true,
      city: {
        cityId: true,
        cityName: true,
      },
    },
  },
  displayLocation: {
    id: true,
    place: true,
  },
};

export const LEGACY_ORDER_COLUMNS = {
  orderId: true,
  orderNumber: true,
  productTitle: true,
  quantity: true,
  originalPrice: true,
  discountUnit: true,
  discountValue: true,
  voucherId: true,
  voucherDiscount: true,
  price: true,
  deliveryCharges: true,
  totalPrice: true,
  status: true,
  notes: true,
  reason: true,
  orderHandledBy: true,
  customerName: true,
  customerEmail: true,
  customerPhone: true,
  customerAddress: true,
  trxMethod: true,
  trxStatus: true,
  trxSessionId: true,
  trxUuid: true,
  trxRefundStatus: true,
  trxRefundReason: true,
  trxRefundDatetime: true,
  trxRefundAmount: true,
  trxRefundId: true,
  createdAt: true,
  updatedAt: true,
  isDeleted: true,
  deletedAt: true,
  listing: {
    listingId: true,
    listingTitle: true,
    effectivePrice: true,
    primaryImage: true,
    effectiveDiscount: true,
    url: true,
    conditionName: true,
    color: true,
    reviews: {
      listingId: true,
      rating: true,
      review: true,
      isPending: true,
    },
  },
  customer: {
    id: true,
    firstName: true,
    lastName: true,
    phoneNumber: true,
    email: true,
  },
  shop: {
    shopId: true,
    shopName: true,
    shopAddress: true,
    owner_whatsapp_number: true,
    location: {
      address: true,
      locationNick: true,
      city: {
        cityId: true,
        cityName: true,
      },
    },
  },
};

export const LISTING_REVIEWS_COLUMNS = {
  rating: true,
  review: true,
  createdAt: true,
  updatedAt: true,
  isDeleted: true,
  isPending: true,
  id: true,
  listing: {
    listingId: true,
    listingTitle: true,
    visits: true,
    isFeatured: true,
    effectiveDiscount: true,
    url: true,
    primaryImage: true,
    status: true,
    activationDate: true,
    archivedOn: true,
    isDeleted: true,
    listedQty: true,
    createdAt: true,
    updatedAt: true,
    effectivePrice: true,
    listingPrice: {
      onlinePrice: true,
    },
    conditionName: true,
    rating: true,
    totalReviews: true,
    totalRatings: true,
    category: true,
    categoryName: true,
    color: true,
    colorName: true,
  },
  user: {
    id: true,
    firstName: true,
    lastName: true,
    phoneNumber: true,
    email: true,
    address: true,
  },
  order: {
    orderId: true,
    orderNumber: true,
    productTitle: true,
    quantity: true,
    originalPrice: true,
    discountUnit: true,
    discountValue: true,
    voucherId: true,
    voucherDiscount: true,
    price: true,
    deliveryCharges: true,
    totalPrice: true,
    notes: true,
    reason: true,
    orderHandledBy: true,
    customerName: true,
    customerEmail: true,
    customerPhone: true,
    customerAddress: true,
    trxMethod: true,
    trxStatus: true,
    trxSessionId: true,
    trxUuid: true,
  },
};

export const CART_COLUMNS = {
  id: true,
  quantity: true,
  totalItems: true,
  totalAmount: true,
  totalDiscount: true,
  isEmpty: true,
  isDummy: true,
  createdAt: true,
  updatedAt: true,
  user: {
    id: true,
    firstName: true,
    lastName: true,
    phoneNumber: true,
    email: true,
    address: true,
  },
  cartItems: {
    id: true,
    cartId: true,
    quantity: true,
    unitPrice: true,
    unitDiscount: true,
    isUpdated: true,
    isNla: true,
    oldPrice: true,
    oldDiscount: true,
    deliveryCharges: true,
    isDummy: true,
    createdAt: true,
    updatedAt: true,
    shop: {
      shopId: true,
      shopName: true,
      address: true,
      logoPath: true,
      username: true,
      onTrial: true,
      onPayment: true,
    },
    listing: {
      listingId: true,
      listingTitle: true,
      url: true,
      listingPrice: {
        onlinePrice: true,
        DiscountUnit: true,
        discountValue: true,
      },
      isFeatured: true,
      activationDate: true,
      listedQty: true,
      effectiveDiscount: true,
      effectivePrice: true,
      imageId: true,
      primaryImage: true,
      location: {
        address: true,
        locationNick: true,
        latitude: true,
        longitude: true,
        city: {
          cityId: true,
          cityName: true,
        },
      },
    },
  },
};

export const USER_ADDRESSES_COLUMNS = {
  id: true,
  streetAddress: true,
  cityId: true,
  provinceId: true,
  city: true,
  province: true,
  country: true,
  isMain: true,
  nearLandmark: true,
  zipCode: true,
  tag: {
    id: true,
    label: true,
  },
  user: {
    id: true,
    firstName: true,
    lastName: true,
    email: true,
    phoneNumber: true,
  },
};

export const ORDER_COLUMNS = {
  id: true,
  orderNumber: true,
  userId: true,
  voucherId: true,
  deliveryChargeId: true,
  deliveryAmount: true,
  isGuest: true,
  guestId: true,
  terms: true,
  reason: true,
  isVoucherApplied: true,
  orderAmount: true,
  quantity: true,
  status: true,
  productDiscount: true,
  voucherDiscount: true,
  cummulativeDiscount: true,
  subTotal: true,
  grandTotal: true,
  eta: true,
  createdAt: true,
  updatedAt: true,
  isDeleted: true,
  orderSources: {
    id: true,
    shopId: {
      shopId: true,
      shopName: true,
      logoPath: true,
      username: true,
      onTrial: true,
      onPayment: true,
      shopOption: {
        id: true,
        isD4uEnabled: true,
        isD4uModuleIncluded: true,
      },
      location: {
        address: true,
        locationNick: true,
        latitude: true,
        longitude: true,
        city: {
          cityId: true,
          cityName: true,
        },
      },
      status: true,
      quantity: true,
      amount: true,
      discountValue: true,
      voucherId: true,
      voucherDiscount: true,
      isDeleted: true,
      createdAt: true,
      updatedAt: true,
    },
  },
};
