import { FilterMap } from '../types/filter-map.type';
import { Model } from '../../modules/models/entities/Model.entity';

export function modelFilters(byCategoryName: string): FilterMap<Model>[] {
  switch (byCategoryName) {
    case 'Laptop':
      return [
        {
          key: 'brandId',
          label: 'brandName',
          alias: 'Brand',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'laptopTypeId',
          label: 'laptopType',
          alias: 'Type',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'processorId',
          label: 'processor',
          alias: 'Processor',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'generationId',
          label: 'generation',
          alias: 'Generation',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'ramTypeId',
          label: 'ramType',
          alias: 'RAM Type',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'ram',
          label: 'ram',
          alias: 'RAM',
          type: 'checkbox',
          unit: 'GB',
        },
        {
          key: 'storageId',
          label: 'storage',
          alias: 'HDD',
          type: 'checkbox',
          unit: 'GB',
        },
        {
          key: 'storageSsdId',
          label: 'storageSsd',
          alias: 'SSD',
          type: 'checkbox',
          unit: 'GB',
        },
        {
          key: 'graphicCardNameId',
          label: 'graphicCardName',
          alias: 'Graphic Card',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'graphicCardTypeId',
          label: 'graphicCardType',
          alias: 'Graphic Card Type',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'graphicCardMemoryId',
          label: 'graphicCardMemory',
          alias: 'Graphic Card Memory',
          type: 'checkbox',
          unit: 'GB',
        },
        {
          key: 'screenSizeId',
          label: 'screenSize',
          alias: 'Screen Size',
          type: 'checkbox',
          unit: 'inch',
        },
        {
          key: 'screenTypeId',
          label: 'screenType',
          alias: 'Screen Type',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'resolutionId',
          label: 'resolution',
          alias: 'Resolution',
          type: 'checkbox',
          unit: 'px',
        },
        {
          key: 'refreshRateId',
          label: 'refreshRate',
          alias: 'Refresh Rate',
          type: 'checkbox',
          unit: 'Hz',
        },
        {
          key: 'speakerId',
          label: 'speaker',
          alias: 'Speaker',
          type: 'checkbox',
          unit: null,
        },
        {
          key: null,
          label: 'hasTouchScreen',
          alias: 'Touch Screen Enabled',
          type: 'radio',
          unit: null,
        },
        {
          key: 'cameraTypeId',
          label: 'cameraType',
          alias: 'Camera Type',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'batteryId',
          label: 'battery',
          alias: 'Battery',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'keyboardId',
          label: 'keyboard',
          alias: 'Keyboard',
          type: 'checkbox',
          unit: null,
        },
        {
          key: null,
          label: 'hasBacklitKeyboard',
          alias: 'Backlit Enabled',
          type: 'radio',
          unit: null,
        },
        {
          key: 'fingerPrintId',
          label: 'fingerPrint',
          alias: 'Finger Print',
          type: 'checkbox',
          unit: null,
        },
      ];
    case 'Mobile':
      return [
        {
          key: 'brandId',
          label: 'brandName',
          alias: 'Brand',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'processorId',
          label: 'processor',
          alias: 'Processor',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'mobileStorageId',
          label: 'mobileStorage',
          alias: 'Storage',
          type: 'checkbox',
          unit: 'GB',
        },
        {
          key: 'ram',
          label: 'ram',
          alias: 'RAM',
          type: 'checkbox',
          unit: 'GB',
        },
        {
          key: 'cameraSpecsId',
          label: 'cameraSpecs',
          alias: 'Camera Specs',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'screenSizeId',
          label: 'screenSize',
          alias: 'Screen Size',
          type: 'checkbox',
          unit: 'inch',
        },
        {
          key: 'screenTypeId',
          label: 'screenType',
          alias: 'Screen Type',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'resolutionId',
          label: 'resolution',
          alias: 'Resolution',
          type: 'checkbox',
          unit: 'px',
        },
        {
          key: 'refreshRateId',
          label: 'refreshRate',
          alias: 'Refresh Rate',
          type: 'checkbox',
          unit: 'Hz',
        },
        {
          key: 'screenProtectionId',
          label: 'screenProtection',
          alias: 'Screen Protection',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'speakerId',
          label: 'speaker',
          alias: 'Speaker',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'batteryCapacity',
          label: 'batteryCapacity',
          alias: 'Battery Capacity',
          type: 'checkbox',
          unit: 'mAh',
        },
        {
          key: 'bodyTypeId',
          label: 'bodyType',
          alias: 'Body Type',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'fingerPrintId',
          label: 'fingerPrint',
          alias: 'Finger Print',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'simTypeId',
          label: 'simType',
          alias: 'SIM Type',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'networkBandsId',
          label: 'networkBands',
          alias: 'Network Bands',
          type: 'checkbox',
          unit: null,
        },
        {
          key: null,
          label: 'hasESim',
          alias: 'E-sim Enabled',
          type: 'radio',
          unit: null,
        },
      ];
    case 'Tablet':
      return [
        {
          key: 'brandId',
          label: 'brandName',
          alias: 'Brand',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'processorId',
          label: 'processor',
          alias: 'Processor',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'mobileStorageId',
          label: 'mobileStorage',
          alias: 'Storage',
          type: 'checkbox',
          unit: 'GB',
        },
        {
          key: 'ram',
          label: 'ram',
          alias: 'RAM',
          type: 'checkbox',
          unit: 'GB',
        },
        {
          key: 'cameraSpecsId',
          label: 'cameraSpecs',
          alias: 'Camera Specs',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'screenSizeId',
          label: 'screenSize',
          alias: 'Screen Size',
          type: 'checkbox',
          unit: 'inch',
        },
        {
          key: 'screenTypeId',
          label: 'screenType',
          alias: 'Screen Type',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'resolutionId',
          label: 'resolution',
          alias: 'Resolution',
          type: 'checkbox',
          unit: 'px',
        },
        {
          key: 'refreshRateId',
          label: 'refreshRate',
          alias: 'Refresh Rate',
          type: 'checkbox',
          unit: 'Hz',
        },
        {
          key: 'screenProtectionId',
          label: 'screenProtection',
          alias: 'Screen Protection',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'speakerId',
          label: 'speaker',
          alias: 'Speaker',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'batteryCapacity',
          label: 'batteryCapacity',
          alias: 'Battery Capacity',
          type: 'checkbox',
          unit: 'mAh',
        },
        {
          key: 'bodyTypeId',
          label: 'bodyType',
          alias: 'Body Type',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'fingerPrintId',
          label: 'fingerPrint',
          alias: 'Finger Print',
          type: 'checkbox',
          unit: null,
        },
        {
          key: null,
          label: 'hasSimSupport',
          alias: 'SIM Supported',
          type: 'radio',
          unit: null,
        },
        {
          key: 'simTypeId',
          label: 'simType',
          alias: 'SIM Type',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'networkBandsId',
          label: 'networkBands',
          alias: 'Network Bands',
          type: 'checkbox',
          unit: null,
        },
        {
          key: null,
          label: 'hasESim',
          alias: 'E-sim Enabled',
          type: 'radio',
          unit: null,
        },
      ];
    case 'TV / Monitor':
      return [
        {
          key: 'brandId',
          label: 'brandName',
          alias: 'Brand',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'screenSizeId',
          label: 'screenSize',
          alias: 'Screen Size',
          type: 'checkbox',
          unit: 'inch',
        },
        {
          key: 'screenTypeId',
          label: 'screenType',
          alias: 'Screen Type',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'resolutionId',
          label: 'resolution',
          alias: 'Resolution',
          type: 'checkbox',
          unit: 'px',
        },
        {
          key: 'refreshRateId',
          label: 'refreshRate',
          alias: 'Refresh Rate',
          type: 'checkbox',
          unit: 'Hz',
        },
        {
          key: 'speakerId',
          label: 'speaker',
          alias: 'Speaker',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'displayTypeId',
          label: 'displayType',
          alias: 'Display Type',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'speakerId',
          label: 'speaker',
          alias: 'Speaker',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'osId',
          label: 'os',
          alias: 'OS',
          type: 'checkbox',
          unit: null,
        },
        {
          key: null,
          label: 'isSmartTv',
          alias: 'Smart TV Enabled',
          type: 'radio',
          unit: null,
        },
        {
          key: null,
          label: 'hasTvCertification',
          alias: 'TV Certification',
          type: 'radio',
          unit: null,
        },
        {
          key: null,
          label: 'hasWebcam',
          alias: 'Webcam Enabled',
          type: 'radio',
          unit: null,
        },
      ];
    case 'Desktop Computer':
      return [
        {
          key: 'brandId',
          label: 'brandName',
          alias: 'Brand',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'desktopTypeId',
          label: 'desktopType',
          alias: 'Type',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'processorId',
          label: 'processor',
          alias: 'Processor',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'generationId',
          label: 'generation',
          alias: 'Generation',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'ramTypeId',
          label: 'ramType',
          alias: 'RAM Type',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'ram',
          label: 'ram',
          alias: 'RAM',
          type: 'checkbox',
          unit: 'GB',
        },
        {
          key: 'storageId',
          label: 'storage',
          alias: 'HDD',
          type: 'checkbox',
          unit: 'GB',
        },
        {
          key: 'storageSsdId',
          label: 'storageSsd',
          alias: 'SSD',
          type: 'checkbox',
          unit: 'GB',
        },
        {
          key: 'graphicCardNameId',
          label: 'graphicCardName',
          alias: 'Graphic Card',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'graphicCardTypeId',
          label: 'graphicCardType',
          alias: 'Graphic Card Type',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'graphicCardMemoryId',
          label: 'graphicCardMemory',
          alias: 'Graphic Card Memory',
          type: 'checkbox',
          unit: 'GB',
        },
        {
          key: 'screenSizeId',
          label: 'screenSize',
          alias: 'Screen Size',
          type: 'checkbox',
          unit: 'inch',
        },
        {
          key: 'screenTypeId',
          label: 'screenType',
          alias: 'Screen Type',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'resolutionId',
          label: 'resolution',
          alias: 'Resolution',
          type: 'checkbox',
          unit: 'px',
        },
        {
          key: 'refreshRateId',
          label: 'refreshRate',
          alias: 'Refresh Rate',
          type: 'checkbox',
          unit: 'Hz',
        },
        {
          key: 'speakerId',
          label: 'speaker',
          alias: 'Speaker',
          type: 'checkbox',
          unit: null,
        },
        {
          key: null,
          label: 'hasTouchScreen',
          alias: 'Touch Screen Enabled',
          type: 'radio',
          unit: null,
        },
        {
          key: null,
          label: 'hasWebcam',
          alias: 'Webcam Enabled',
          type: 'radio',
          unit: null,
        },
      ];
    case 'Accessories':
      return [
        {
          key: 'brandId',
          label: 'brandName',
          alias: 'Brand',
          type: 'checkbox',
          unit: null,
        },
        {
          key: 'accessoryTypeId',
          label: 'accessoryType',
          alias: 'Type',
          type: 'checkbox',
          unit: null,
        },
      ];
    default:
      throw new Error('Invalid category name / category not found / category not implemented');
  }
}
