import { FilterDefinition, FilterSource, FilterType } from '../types/filter.types';

// Common filters that apply to all categories
export const COMMON_FILTERS: FilterDefinition[] = [
  {
    name: 'categoryName',
    label: 'Category',
    type: FilterType.RADIO,
    source: FilterSource.LISTING,
    dbColumn: 'category_name',
    isCommon: true,
  },
  {
    name: 'conditionName',
    label: 'Condition',
    type: FilterType.CHECKBOX,
    source: FilterSource.LISTING,
    dbColumn: 'condition_name',
    isCommon: true,
  },
  {
    name: 'cityName',
    label: 'City',
    type: FilterType.CHECKBOX,
    source: FilterSource.LISTING,
    dbColumn: 'city_name',
    isCommon: true,
    // City name requires joining with the city table
    join: {
      table: 'city',
      alias: 'c',
      onColumn: 'city_id', // listing.city_id
      joinColumn: 'city_id', // city.city_id
      selectColumn: 'city_name', // city.city_name
    },
  },
  {
    name: 'brandName',
    label: 'Brand',
    type: FilterType.CHECKBOX,
    source: FilterSource.LISTING,
    dbColumn: 'brand_name',
    isCommon: true,
  },
  {
    name: 'colorName',
    label: 'Color',
    type: FilterType.CHECKBOX,
    source: FilterSource.LISTING,
    dbColumn: 'color',
    isCommon: true,
  },
  {
    name: 'price',
    label: 'Price',
    type: FilterType.RANGE,
    source: FilterSource.LISTING,
    dbColumn: 'effective_price',
    isCommon: true,
    unit: 'PKR',
  },
];

// Category-specific filters
export const CATEGORY_FILTERS: Record<string, FilterDefinition[]> = {
  Laptop: [
    {
      name: 'model',
      label: 'Model',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'model',
      isCategorySpecific: true,
      categories: ['Laptop', 'Desktop Computer', 'Mobile', 'Tablet', 'TV / Monitor', 'Accessories'],
    },
    {
      name: 'laptopType',
      label: 'Laptop Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'laptop_type',
      isCategorySpecific: true,
      categories: ['Laptop'],
    },
    {
      name: 'processor',
      label: 'Processor',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'processor',
      isCategorySpecific: true,
      categories: ['Laptop', 'Mobile', 'Tablet'],
    },
    {
      name: 'generation',
      label: 'Generation',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'generation',
      isCategorySpecific: true,
      categories: ['Laptop'],
    },
    {
      name: 'ramType',
      label: 'RAM Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'ram_type',
      isCategorySpecific: true,
      categories: ['Laptop'],
    },
    {
      name: 'ramCapacity',
      label: 'RAM Capacity',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'ram_capacity',
      isCategorySpecific: true,
      unit: 'GB',
      categories: ['Laptop'],
    },
    {
      name: 'primaryStorageType',
      label: 'Primary Storage Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'primary_storage_type',
      isCategorySpecific: true,
      categories: ['Laptop'],
    },
    {
      name: 'primaryStorageCapacity',
      label: 'Primary Storage Capacity',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'primary_storage_capacity',
      isCategorySpecific: true,
      unit: 'GB',
      categories: ['Laptop'],
    },
    {
      name: 'secondaryStorageType',
      label: 'Secondary Storage Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'secondary_storage_type',
      isCategorySpecific: true,
      categories: ['Laptop'],
    },
    {
      name: 'secondaryStorageCapacity',
      label: 'Secondary Storage Capacity',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'secondary_storage_capacity',
      isCategorySpecific: true,
      unit: 'GB',
      categories: ['Laptop'],
    },
    {
      name: 'graphicsCardName',
      label: 'Graphics Card Name',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'graphics_card_name',
      isCategorySpecific: true,
      categories: ['Laptop'],
    },
    {
      name: 'graphicsCardType',
      label: 'Graphics Card Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'graphics_card_type',
      isCategorySpecific: true,
      categories: ['Laptop'],
    },
    {
      name: 'graphicsCardMemory',
      label: 'Graphics Card Memory',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'graphics_card_memory',
      isCategorySpecific: true,
      unit: 'MB',
      categories: ['Laptop'],
    },
    {
      name: 'screenSize',
      label: 'Screen Size',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'screen_size',
      isCategorySpecific: true,
      unit: 'Inch',
      categories: ['Laptop', 'Mobile', 'Tablet'],
    },
    {
      name: 'screenType',
      label: 'Screen Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'screen_type',
      isCategorySpecific: true,
      categories: ['Laptop', 'Mobile', 'Tablet'],
    },
    {
      name: 'resolution',
      label: 'Screen Resolution',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'resolution',
      isCategorySpecific: true,
      categories: ['Laptop', 'Mobile', 'Tablet'],
    },
    {
      name: 'isTouchScreen',
      label: 'Touch Screen',
      type: FilterType.BOOLEAN,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'is_touch_screen',
      isCategorySpecific: true,
      categories: ['Laptop'],
    },
    {
      name: 'isBacklitKeyboard',
      label: 'Backlit Keyboard',
      type: FilterType.BOOLEAN,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'is_backlit_keyboard',
      isCategorySpecific: true,
      categories: ['Laptop'],
    },
    {
      name: 'keyboard',
      label: 'Keyboard',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'keyboard',
      isCategorySpecific: true,
      categories: ['Laptop'],
    },
    {
      name: 'speaker',
      label: 'Speakers',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'speaker',
      isCategorySpecific: true,
      categories: ['Laptop'],
    },
    {
      name: 'batteryType',
      label: 'Battery Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'battery_type',
      isCategorySpecific: true,
      categories: ['Laptop'],
    },
    {
      name: 'fingerprint',
      label: 'Fingerprint',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'fingerprint',
      isCategorySpecific: true,
      categories: ['Laptop', 'Mobile', 'Tablet'],
    },
  ],
  Mobile: [
    {
      name: 'model',
      label: 'Model',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'model',
      isCategorySpecific: true,
      categories: ['Laptop', 'Desktop Computer', 'Mobile', 'Tablet', 'TV / Monitor', 'Accessories'],
    },
    {
      name: 'ramCapacity',
      label: 'RAM',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'ram_capacity',
      isCategorySpecific: true,
      unit: 'GB',
      categories: ['Mobile', 'Tablet'],
    },
    {
      name: 'primaryStorageCapacity',
      label: 'Storage',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'primary_storage_capacity',
      isCategorySpecific: true,
      unit: 'GB',
      categories: ['Mobile', 'Tablet'],
    },
    {
      name: 'cameraSpecs',
      label: 'Camera Specs',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'camera_specs',
      isCategorySpecific: true,
      categories: ['Mobile', 'Tablet'],
    },
    {
      name: 'screenType',
      label: 'Screen Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'screen_type',
      isCategorySpecific: true,
      categories: ['Mobile', 'Tablet'],
    },
    {
      name: 'screenSize',
      label: 'Screen Size',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'screen_size',
      isCategorySpecific: true,
      unit: 'Inch',
      categories: ['Mobile', 'Tablet'],
    },
    {
      name: 'screenProtection',
      label: 'Screen Protection',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'screen_protection',
      isCategorySpecific: true,
      categories: ['Mobile', 'Tablet'],
    },
    {
      name: 'resolution',
      label: 'Screen Resolution',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'resolution',
      isCategorySpecific: true,
      categories: ['Laptop', 'Mobile', 'Tablet'],
    },
    {
      name: 'refreshRate',
      label: 'Refresh Rate',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'refresh_rate',
      isCategorySpecific: true,
      unit: 'Hz',
      categories: ['Mobile', 'Tablet'],
    },
    {
      name: 'batteryCapacity',
      label: 'Battery Capacity',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'battery_capacity',
      isCategorySpecific: true,
      unit: 'mAh',
      categories: ['Mobile', 'Tablet'],
    },
    {
      name: 'isPtaApproved',
      label: 'PTA Approved',
      type: FilterType.BOOLEAN,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'is_pta_approved',
      isCategorySpecific: true,
      categories: ['Mobile', 'Tablet'],
    },
    {
      name: 'networkBand',
      label: 'Network Band',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'network_band',
      isCategorySpecific: true,
      categories: ['Mobile'],
    },
    {
      name: 'simType',
      label: 'SIM Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'sim_type',
      isCategorySpecific: true,
      categories: ['Mobile'],
    },
    {
      name: 'isESim',
      label: 'E-SIM Support',
      type: FilterType.BOOLEAN,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'is_e_sim',
      isCategorySpecific: true,
      categories: ['Mobile'],
    },
    {
      name: 'processor',
      label: 'Processor',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'processor',
      isCategorySpecific: true,
      categories: ['Laptop', 'Mobile', 'Tablet'],
    },
    {
      name: 'fingerprint',
      label: 'Fingerprint',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'fingerprint',
      isCategorySpecific: true,
      categories: ['Laptop', 'Mobile', 'Tablet'],
    },
  ],
  Tablet: [
    {
      name: 'model',
      label: 'Model',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'model',
      isCategorySpecific: true,
      categories: ['Laptop', 'Desktop Computer', 'Mobile', 'Tablet', 'TV / Monitor', 'Accessories'],
    },
    {
      name: 'ramCapacity',
      label: 'RAM',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'ram_capacity',
      isCategorySpecific: true,
      unit: 'GB',
      categories: ['Mobile', 'Tablet'],
    },
    {
      name: 'primaryStorageCapacity',
      label: 'Storage',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'primary_storage_capacity',
      isCategorySpecific: true,
      unit: 'GB',
      categories: ['Mobile', 'Tablet'],
    },
    {
      name: 'cameraSpecs',
      label: 'Camera Specs',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'camera_specs',
      isCategorySpecific: true,
      categories: ['Mobile', 'Tablet'],
    },
    {
      name: 'screenType',
      label: 'Screen Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'screen_type',
      isCategorySpecific: true,
      categories: ['Mobile', 'Tablet'],
    },
    {
      name: 'screenSize',
      label: 'Screen Size',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'screen_size',
      isCategorySpecific: true,
      unit: 'Inch',
      categories: ['Mobile', 'Tablet'],
    },
    {
      name: 'screenProtection',
      label: 'Screen Protection',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'screen_protection',
      isCategorySpecific: true,
      categories: ['Mobile', 'Tablet'],
    },
    {
      name: 'resolution',
      label: 'Screen Resolution',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'resolution',
      isCategorySpecific: true,
      categories: ['Laptop', 'Mobile', 'Tablet'],
    },
    {
      name: 'refreshRate',
      label: 'Refresh Rate',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'refresh_rate',
      isCategorySpecific: true,
      unit: 'Hz',
      categories: ['Mobile', 'Tablet'],
    },
    {
      name: 'batteryCapacity',
      label: 'Battery Capacity',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'battery_capacity',
      isCategorySpecific: true,
      unit: 'mAh',
      categories: ['Mobile', 'Tablet'],
    },
    {
      name: 'isPtaApproved',
      label: 'PTA Approved',
      type: FilterType.BOOLEAN,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'is_pta_approved',
      isCategorySpecific: true,
      categories: ['Mobile', 'Tablet'],
    },
    {
      name: 'networkBand',
      label: 'Network Band',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'network_band',
      isCategorySpecific: true,
      categories: ['Mobile'],
    },
    {
      name: 'simType',
      label: 'SIM Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'sim_type',
      isCategorySpecific: true,
      categories: ['Mobile'],
    },
    {
      name: 'isESim',
      label: 'E-SIM Support',
      type: FilterType.BOOLEAN,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'is_e_sim',
      isCategorySpecific: true,
      categories: ['Mobile'],
    },
    {
      name: 'processor',
      label: 'Processor',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'processor',
      isCategorySpecific: true,
      categories: ['Laptop', 'Mobile', 'Tablet'],
    },
    {
      name: 'fingerprint',
      label: 'Fingerprint',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'fingerprint',
      isCategorySpecific: true,
      categories: ['Laptop', 'Mobile', 'Tablet'],
    },
    {
      name: 'isSimSupport',
      label: 'SIM Support',
      type: FilterType.BOOLEAN,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'is_sim_support',
      isCategorySpecific: true,
      categories: ['Tablet'],
    },
  ],
  'TV / Monitor': [
    {
      name: 'model',
      label: 'Model',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'model',
      isCategorySpecific: true,
      categories: ['Laptop', 'Desktop Computer', 'Mobile', 'Tablet', 'TV / Monitor', 'Accessories'],
    },
    {
      name: 'screenSize',
      label: 'Screen Size',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'screen_size',
      isCategorySpecific: true,
      unit: 'Inch',
      categories: ['TV / Monitor'],
    },
    {
      name: 'screenType',
      label: 'Screen Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'screen_type',
      isCategorySpecific: true,
      categories: ['TV / Monitor'],
    },
    {
      name: 'resolution',
      label: 'Resolution',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'resolution',
      isCategorySpecific: true,
      categories: ['TV / Monitor'],
    },
    {
      name: 'refreshRate',
      label: 'Refresh Rate',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'refresh_rate',
      isCategorySpecific: true,
      unit: 'Hz',
      categories: ['TV / Monitor'],
    },
    {
      name: 'displayType',
      label: 'Display Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'display_type',
      isCategorySpecific: true,
      categories: ['TV / Monitor'],
    },
    {
      name: 'tvMonitorType',
      label: 'Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'tv_monitor_type',
      isCategorySpecific: true,
      categories: ['TV / Monitor'],
    },
    {
      name: 'isSmartTv',
      label: 'Smart TV',
      type: FilterType.BOOLEAN,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'is_smart_tv',
      isCategorySpecific: true,
      categories: ['TV / Monitor'],
    },
    {
      name: 'isWebcam',
      label: 'Webcam Support',
      type: FilterType.BOOLEAN,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'is_webcam',
      isCategorySpecific: true,
      categories: ['TV / Monitor'],
    },
    {
      name: 'isTvCertified',
      label: 'TV Certified',
      type: FilterType.BOOLEAN,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'is_tv_certified',
      isCategorySpecific: true,
      categories: ['TV / Monitor'],
    },
    {
      name: 'speaker',
      label: 'Speakers',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'speaker',
      isCategorySpecific: true,
      categories: ['TV / Monitor'],
    },
  ],
  'Desktop Computer': [
    {
      name: 'model',
      label: 'Model',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'model',
      isCategorySpecific: true,
      categories: ['Laptop', 'Desktop Computer', 'Mobile', 'Tablet', 'TV / Monitor', 'Accessories'],
    },
    {
      name: 'desktopType',
      label: 'Desktop Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'desktop_type',
      isCategorySpecific: true,
      categories: ['Desktop Computer'],
    },
    {
      name: 'processor',
      label: 'Processor',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'processor',
      isCategorySpecific: true,
      categories: ['Laptop', 'Desktop Computer', 'Mobile', 'Tablet'],
    },
    {
      name: 'generation',
      label: 'Generation',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'generation',
      isCategorySpecific: true,
      categories: ['Desktop Computer'],
    },
    {
      name: 'ramType',
      label: 'RAM Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'ram_type',
      isCategorySpecific: true,
      categories: ['Desktop Computer'],
    },
    {
      name: 'ramCapacity',
      label: 'RAM Capacity',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'ram_capacity',
      isCategorySpecific: true,
      unit: 'GB',
      categories: ['Desktop Computer'],
    },
    {
      name: 'primaryStorageType',
      label: 'Storage Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'primary_storage_type',
      isCategorySpecific: true,
      categories: ['Desktop Computer'],
    },
    {
      name: 'primaryStorageCapacity',
      label: 'Storage Capacity',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'primary_storage_capacity',
      isCategorySpecific: true,
      unit: 'GB',
      categories: ['Desktop Computer'],
    },
    {
      name: 'secondaryStorageType',
      label: 'Secondary Storage Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'secondary_storage_type',
      isCategorySpecific: true,
      categories: ['Laptop'],
    },
    {
      name: 'secondaryStorageCapacity',
      label: 'Secondary Storage Capacity',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'secondary_storage_capacity',
      isCategorySpecific: true,
      unit: 'GB',
      categories: ['Laptop'],
    },
    {
      name: 'graphicsCardName',
      label: 'Graphics Card Name',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'graphics_card_name',
      isCategorySpecific: true,
      categories: ['Laptop'],
    },
    {
      name: 'graphicsCardType',
      label: 'Graphics Card Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'graphics_card_type',
      isCategorySpecific: true,
      categories: ['Laptop'],
    },
    {
      name: 'graphicsCardMemory',
      label: 'Graphics Card Memory',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'graphics_card_memory',
      isCategorySpecific: true,
      unit: 'MB',
      categories: ['Laptop'],
    },
    {
      name: 'screenSize',
      label: 'Screen Size',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'screen_size',
      isCategorySpecific: true,
      unit: 'Inch',
      categories: ['Laptop', 'Mobile', 'Tablet'],
    },
    {
      name: 'resolution',
      label: 'Screen Resolution',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'resolution',
      isCategorySpecific: true,
      categories: ['Laptop', 'Mobile', 'Tablet'],
    },
    {
      name: 'isTouchScreen',
      label: 'Touch Screen',
      type: FilterType.BOOLEAN,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'is_touch_screen',
      isCategorySpecific: true,
      categories: ['Laptop'],
    },
  ],
  Accessories: [
    {
      name: 'model',
      label: 'Model',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'model',
      isCategorySpecific: true,
      categories: ['Laptop', 'Desktop Computer', 'Mobile', 'Tablet', 'TV / Monitor', 'Accessories'],
    },
    {
      name: 'accessoryType',
      label: 'Accessory Type',
      type: FilterType.CHECKBOX,
      source: FilterSource.SPECIFICATION,
      dbColumn: 'accessory_type',
      isCategorySpecific: true,
      categories: ['Accessories'],
    },
  ],
};

// Get filters for a specific category
export function getFiltersForCategory(categoryName: string): FilterDefinition[] {
  return CATEGORY_FILTERS[categoryName] || [];
}

// Get all unique filter names from all categories
export function getAllUniqueFilters(): string[] {
  const allFilters = new Set<string>();

  // Add common filters
  COMMON_FILTERS.forEach(filter => allFilters.add(filter.name));

  // Add category-specific filters
  Object.values(CATEGORY_FILTERS).forEach(filters => {
    filters.forEach(filter => allFilters.add(filter.name));
  });

  return Array.from(allFilters);
}

// Get filter definition by name
export function getFilterByName(filterName: string, categoryName?: string): FilterDefinition | undefined {
  // Check common filters first
  const commonFilter = COMMON_FILTERS.find(f => f.name === filterName);
  if (commonFilter) return commonFilter;

  // Check category-specific filters
  if (categoryName) {
    const categoryFilters = CATEGORY_FILTERS[categoryName] || [];
    return categoryFilters.find(f => f.name === filterName);
  }

  // Search all categories
  for (const filters of Object.values(CATEGORY_FILTERS)) {
    const filter = filters.find(f => f.name === filterName);
    if (filter) return filter;
  }

  return undefined;
}
