import { ListingsQueryDto } from '@modules/listings/dtos/listings-query.dto';

export type ListingFilterName = keyof Omit<ListingsQueryDto, 'page' | 'size' | 'sort' | 'search' | 'store'>;

export const LISTING_FILTER_NAMES = [
  'categoryName',
  'cityName',
  'conditionName',
  'brandName',
  'minPrice',
  'maxPrice',
  'model',
  'colorName',
  'laptopType',
  'ramType',
  'ramCapacity',
  'primaryStorageType',
  'primaryStorageCapacity',
  'secondaryStorageType',
  'secondaryStorageCapacity',
  'processor',
  'generation',
  'graphicsCardName',
  'graphicsCardType',
  'graphicsCardMemory',
  'screenSize',
  'screenType',
  'screenProtection',
  'resolution',
  'keyboard',
  'speaker',
  'batteryType',
  'batteryCapacity',
  'isTouchScreen',
  'isBacklitKeyboard',
  'fingerprint',
  'isPtaApproved',
  'cameraSpecs',
  'isESim',
  'networkBand',
  'refreshRate',
  'simType',
  'bodyType',
  'isSimSupport',
  'displayType',
  'operatingSystem',
  'isSmartTv',
  'isWebcam',
  'isTvCertified',
  'desktopType',
  'accessoryType',
  'tvMonitorType',
] as const;
